GET http://localhost:8000/items

###
GET http://localhost:8000/items/1

###
POST http://localhost:8000/items
Content-Type: application/json

{
  "name": "Mac",
  "price": 30000
}

###
PUT http://localhost:8000/items/1
Content-Type: application/json

{
  "name": "Ahora ya se",
  "price": 100
}

###
DELETE http://localhost:8000/items/9

###
POST http://localhost:8000/login
Content-Type: application/json

{
  "username": "luis",
  "password": "123"
}